name: CI/CD for DevOps App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run FastAPI App (Test Boot)
        run: |
          nohup uvicorn main:app --port 8000 &
          sleep 5
          curl -f http://localhost:8000 || exit 1

      - name: Log in to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/your-github-username/worldwithweb-devops-app:latest .

      - name: Push Docker image to GHCR
        run: docker push ghcr.io/your-github-username/worldwithweb-devops-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker stop worldwithweb-devops-app || true
            docker rm worldwithweb-devops-app || true
            docker pull ghcr.io/your-github-username/worldwithweb-devops-app:latest
            docker run -d --name worldwithweb-devops-app -p 8000:8000 ghcr.io/your-github-username/worldwithweb-devops-app:latest
