# name: Terraform CI/CD

# on:
#   push:
#     paths:
#       - 'terraform/**'
#       - '.github/workflows/terraform.yml'
#   workflow_dispatch:
#     inputs:
#         auto_apply:
#             description: 'Auto apply the changes?'
#             required: true
#             default: 'false'
          

# env:
#   TF_VAR_key_name: worldwithweb-key
#   TF_VAR_region: ap-south-1b

# jobs:
#   terraform:
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: terraform

#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v3

#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v2

#       - name: Terraform Init
#         run: terraform init

#       - name: Terraform Format
#         run: terraform fmt -check

#       - name: Terraform Plan
#         run: terraform plan

#       - name: Terraform Apply (Conditional)
#         if: github.event.inputs.auto_apply == 'true'
#         run: terraform apply -auto-approve
